image: ruby
env:
  - PATH=${HOME}/.rbenv/versions/${RBENV_VERSION}/bin:$PATH
script:
  - bundle install
  - bundle exec rake spec
  - bundle exec rake lint
  - bundle exec rake validate
notify:
  email:
    recipients:
      - christj@gmail.com
