image: ruby
env:
  - PATH=${HOME}/.rbenv/versions/${RBENV_VERSION}/bin:$PATH
script:
  - gem install puppet-lint
  - puppet-lint ${DRONE_BUILD_DIR} --no-class_inherits_from_params_class-check --no-documentation-check --fail-on-warnings
notify:
  email:
    recipients:
      - christj@gmail.com
