language: ruby
rvm:
 - "1.8.7"
 - "1.9.2"
 - "1.9.3"
 - "2.1.1"
# uncomment this line if your project needs to run something other than `rake`:
script:
  - bundle exec rake spec
  - bundle exec rake lint
  - bundle exec rake validate
notifications:
  email:
    - christj@gmail.com
