# This file is generated by ModuleSync, do not edit.
require 'puppetlabs_spec_helper/module_spec_helper'
require 'pry'

if Puppet.version.to_f >= 4.5
  RSpec.configure do |c|
    c.before :each do
      Puppet.settings[:strict] = :error
    end
  end
end

RSpec.configure do |c|
  c.after(:suite) do
    at_exit(exit(1)) if RSpec::Puppet::Coverage.report!(90)
  end
end

# put local configuration and setup into spec_helper_local
begin
  require 'spec_helper_local'
rescue LoadError
  puts 'error loading spec_helper_local'
end
